### PR TITLE
Build lua as cpp

### PR DESCRIPTION
**Pull request by illegal-instruction-co**
Build lua as cpp

Why would you want to compile lua to C when you can do everything via CPP? Don't you think CPP exceptions are cooler?

try {} catch(...) {}
__try { } __except(filter){}

### CODE REVIEW

**Comment by illegal-instruction-co** [comment]
http://lua-users.org/wiki/BuildingLua

**Comment by illegal-instruction-co** [comment]
Also check these out guzel kardesim
https://github.com/illegal-instruction-co/NtLua/commit/4e5667397bfa93c3bc260a8638c4b99f85b89bbb

**Comment by can1357** [comment]
We do not use LUAI_THROW, instead it's handled in the panic function via setjmp and longjmp. You cannot use C++ exceptions in the kernel without the appropriate runtime support which isn't in ntoskrnl and there is no justifiable reason to implement them either since setjmp and longjmp does what we want it to do.

**Comment by illegal-instruction-co** [comment]
Thank you for your quick reply, by the way I really enjoyed your work. My only purpose in this commit was to try, test and learn. I just felt the need to play around here and as you said, the old version was actually working fine.

**Pull request closed without merging**
